name: CI/CD パイプライン

on:
  push:
    branches:
      - main
      - add_contract
  pull_request:
    branches:
      - main

jobs:
  test-contract:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contract

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.x"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Compile contracts
        run: bun run compile

      - name: Run tests
        run: bun run test
